# config/packages/meilisearch.yaml
meilisearch:
    url: '%env(MEILISEARCH_URL)%'
    api_key: '%env(MEILISEARCH_API_KEY)%'
    prefix: '%env(MEILISEARCH_PREFIX)%'

    indices:
        -   name: 'assets'
            class: 'App\Entity\Assets\Assets'

            # FIX: The correct key is "serializer_groups"
            serializer_groups:
                - 'searchable'

            settings:
                searchableAttributes:
                    - 'name'
                    - 'itemCodesForSearch'
                    - 'tagsForSearch'
                    - 'brandForSearch.name'
                    - 'categoriesForSearch.name'
                    - 'collectionsForSearch.name'
                    - 'description'
                rankingRules:
                    - 'exactness'
                    - 'words'
                    - 'typo'
                    - 'proximity'
                    - 'attribute'
                    - 'sort'
                filterableAttributes:
                    - 'parent_brand_ids'
                    - 'brand'
                    - 'categories'
                    - 'collections'
                    - 'status'
                    - 'embargodate'
                    - 'brandForSearch.status'
                    - 'categoriesForSearch.status'
                    - 'collectionsForSearch.status'
                    - 'brandForSearch.id'
                    - 'categoriesForSearch.id'
                    - 'collectionsForSearch.id'
