# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_dir: '%kernel.project_dir%/files'
    thumbnail_dir: '%kernel.project_dir%/files-thumbs'
    ai_dir: '%kernel.project_dir%/files-ai'
    cag_dir: '%kernel.project_dir%/docs/business'
    direct_uploads_dir: '%kernel.project_dir%/files-direct'
    srgb_profile_path: '%kernel.project_dir%/config/color-icc/rgb/AdobeRGB1998.icc'
    cmyk_profile_path: '%kernel.project_dir%/config/color-icc/cmyk/USWebCoatedSWOP.icc'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $uploadDir: '%upload_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Security\UserProvider:
        arguments:
            - '@App\Repository\UserRepository'

    App\Doctrine\BrandFilter:
        autowire: true
        calls:
            -   method: setSecurity
                arguments:
                    - '@security.helper'

    App\Controller\Chat\ChatController:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $gcpProjectId: '%env(GOOGLE_PROJECT_ID)%'
            $gcpLocation: '%env(GOOGLE_LOCATION)%'

    App\Command\CacheBusinessInfoCommand:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $cagDir: '%cag_dir%'

    # App\EventListener\MeilisearchAssetsAttributesSyncListener:
    #     tags:
    #         - { name: doctrine.event_subscriber, connection: default }
